### ISSUE TITLE
No .gitignore configuration

### ISSUE THREAD

**Issue by ajayns** [therohitramesh/todo-node.js#1]
`node_modules` contains all dependencies and these vary with system and local environment, so for each system `npm install` should be done for installation. Therefore, `node_modules` is never uploaded in the source of a git project. 

Read about `.gitignore` and add it to the project.

**Comment by ajayns** [comment]
@therohitramesh Resolve!

**Comment by therohitramesh** [comment]
Ok got it. Thanks @ajayns !
